config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :apartments do
    get 'map_location'
    get 'map_locations', on: :collection
  end

  get "admin" => "admin#index"
  put 'admin/:id' => 'admin#update'
  patch 'admin/:id' => 'admin#update'
  root "apartments#page"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.nil?
      user = User.new
    end

    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :owner
      can :manage, Apartment
    elsif user.has_role? :resident
      can :read, Apartment, user_id: user.id
    else
      can :read, :all
    end
  end

end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

app/models/apartment.rb
class Apartment < ActiveRecord::Base
  belongs_to :user
  geocoded_by :full_address
  after_validation :geocode
  validates :user, presence: true
  resourcify

  def full_address
    [address_1, city, state, country].compact.join(', ')
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :apartments
  after_create :assign_role
  #before_create :check_roles
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:twitter]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.uid + "@twitter.com"
      user.password = Devise.friendly_token[0,20]
    end
  end

  def assign_role
    add_role(:resident)
  end

  # def check_roles
  #   if !(current_user.roles.length > 0)
  #     redirect_to '/'
  #   end
  # end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize

  def index
    @users = User.all
  end

  def update
    user = User.find(params[:id])
    new_role = params[:role]
    user.remove_role ''
    user.remove_role :resident
    user.remove_role "Make Admin"
    #new_role = Role.find_by_name(params[:role])
    user.add_role new_role
    redirect_to '/admin'
  end

  private
    def authorize
      if !current_user.has_role? :admin
        render text:"No access for you!"
      end
    end
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:page, :index, :show, :map_location, :map_locations] #add this line

  load_and_authorize_resource
  skip_authorize_resource only: [:page, :map_location, :map_locations]

  def page
  end
  # GET /apartments
  # GET /apartments.json
  def index
    if !user_signed_in?
      @ability = Ability.new(User.new())
    else
      @ability = Ability.new(current_user)
    end

    if !user_signed_in? || (@ability.can? :manage, Apartment)
      @apartments = Apartment.all
    else
      @apartments = Apartment.where(user_id: current_user.id)
    end
  end

  # GET /apartments/1
  # GET /apartments/1.json
  def show
  end

  def map_location
    @apartment = Apartment.find(params[:apartment_id])
    @hash = Gmaps4rails.build_markers(@apartment) do |apartment, marker|
      marker.lat(apartment.latitude)
      marker.lng(apartment.longitude)
      marker.infowindow("<em>" + apartment.address_1 + "</em>")
    end
    render json: @hash.to_json
  end

  def map_locations
    if !user_signed_in?
      @ability = Ability.new(User.new())
    else
      @ability = Ability.new(current_user)
    end
    if !user_signed_in? || (@ability.can? :manage, Apartment)
      @apartments = Apartment.all
    else
      @apartments = Apartment.where(user_id: current_user.id)
    end
    @hash = Gmaps4rails.build_markers(@apartments) do |apartment, marker|
      marker.lat(apartment.latitude)
      marker.lng(apartment.longitude)
      #marker.infowindow("<em>" + apartment.address_1 + "</em>")
    end
    render json: @hash.to_json
  end

  # GET /apartments/new
  def new
    @apartment = current_user.apartments.build
  end
  #100 Park Blvd, San Diego, CA 92101
  #Address: 1 Royal Way, Kansas City, MO 64129
  # 700 Clark Ave, St. Louis, MO 63102


  # GET /apartments/1/edit
  def edit
    if @apartment.user == current_user
      render
    else
      redirect_to apartments_path, notice: "Wrong!"
    end
  end

  # POST /apartments
  # POST /apartments.json
  def create
    @apartment = current_user.apartments.build(apartment_params)

    respond_to do |format|
      if @apartment.save
        format.html { redirect_to @apartment, notice: 'Apartment was successfully created.' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1
  # PATCH/PUT /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to @apartment, notice: 'Apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1
  # DELETE /apartments/1.json
  def destroy
    if @apartment.user == current_user
      @apartment.destroy
      respond_to do |format|
        format.html { redirect_to apartments_url, notice: 'Apartment was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to apartments_path, notice: "Wrong!"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartment_params
      params.require(:apartment).permit(:address_1, :address_2, :city, :zip, :state, :country, :name, :phone, :contact_hrs_from, :contact_hrs_to)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env["omniauth.auth"])
      if @user.persisted?
        sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
        set_flash_message(:notice, :success, :kind => "twitter") if is_navigational_format?
      else
        session["devise.twitter_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end
    def failure
      redirect_to root_path
    end
  end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.erb
<h1>Users</h1>
<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Role</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.roles.first.name %></td>
        <td>
          <%= link_to "Make Admin", admin_path + '/' + user.id.to_s + '?role=admin', method: :PUT %>
          <%= link_to "Make Owner", admin_path + '/' + user.id.to_s + '?role=owner', method: :PUT%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/update.html.erb
<h1>Admin#update</h1>
<p>Find me in app/views/admin/update.html.erb</p>

app/views/apartments/_form.html.erb
<%= form_for(@apartment) do |f| %>
  <% if @apartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>

      <ul>
      <% @apartment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address_1 %><br>
    <%= f.text_field :address_1 %>
  </div>
  <div class="field">
    <%= f.label :address_2 %><br>
    <%= f.text_field :address_2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.number_field :zip %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :contact_hrs_from %><br>
    <%= f.time_select :contact_hrs_from %>
  </div>
  <div class="field">
    <%= f.label :contact_hrs_to %><br>
    <%= f.time_select :contact_hrs_to %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apartments/edit.html.erb
<h1>Editing Apartment</h1>

<%= render 'form' %>

<%= link_to 'Show', @apartment %> |
<%= link_to 'Back', apartments_path %>

app/views/apartments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Apartments</h1>

<table>
  <thead>
    <tr>
      <th>Address 1</th>
      <th>Address 2</th>
      <th>City</th>
      <th>Zip</th>
      <th>State</th>
      <th>Country</th>
      <th>Name</th>
      <th>Phone</th>
      <th>Contact hrs from</th>
      <th>Contact hrs to</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apartments.each do |apartment| %>
    <% if @ability.can? :read, apartment %>
      <tr>
        <td><%= apartment.address_1 %></td>
        <td><%= apartment.address_2 %></td>
        <td><%= apartment.city %></td>
        <td><%= apartment.zip %></td>
        <td><%= apartment.state %></td>
        <td><%= apartment.country %></td>
        <td><%= apartment.name %></td>
        <td><%= apartment.phone %></td>
        <td><%= apartment.contact_hrs_from %></td>
        <td><%= apartment.contact_hrs_to %></td>
        <td><%= apartment.latitude %></td>
        <td><%= apartment.longitude %></td>
        <td><%= link_to 'Show', apartment %></td>
        <% if @ability.can? :manage, apartment %>
          <td><%= link_to 'Edit', edit_apartment_path(apartment) %></td>
          <td><%= link_to 'Destroy', apartment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>

<% if @ability.can? :manage, Apartment %>
  <%= link_to 'New Apartment', new_apartment_path %>
<% end %>
<div id="apartment_maps"> google maps will be placed here </div>

app/views/apartments/new.html.erb
<h1>New Apartment</h1>

<%= render 'form' %>

<%= link_to 'Back', apartments_path %>

app/views/apartments/page.html.erb
<h1> All greats pass through here! </h1>

app/views/apartments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address 1:</strong>
  <%= @apartment.address_1 %>
</p>

<p>
  <strong>Address 2:</strong>
  <%= @apartment.address_2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @apartment.city %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @apartment.zip %>
</p>

<p>
  <strong>State:</strong>
  <%= @apartment.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @apartment.country %>
</p>

<p>
  <strong>Name:</strong>
  <%= @apartment.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @apartment.phone %>
</p>

<p>
  <strong>Contact hrs from:</strong>
  <%= @apartment.contact_hrs_from %>
</p>

<p>
  <strong>Contact hrs to:</strong>
  <%= @apartment.contact_hrs_to %>
</p>

<p>
  <strong>Latitude</strong>
  <%= @apartment.latitude %>
</p>

<p>
  <strong>Longitude</strong>
  <%= @apartment.longitude %>
</p>

<%= link_to 'Edit', edit_apartment_path(@apartment) %> |
<%= link_to 'Back', apartments_path %>

<div id="apartment_map" data-apartment-id="<%= @apartment.id %>">Google Map will appear here...</div>

app/views/layouts/_header.html.erb
<nav>
  <%= link_to "Home", '/' %>
  <%= link_to "Apartments", '/apartments' %>
  <% if !user_signed_in? %>
    <%= link_to "Log-in", new_user_session_path %>
    <%= link_to "Sign in with Twitter", user_twitter_omniauth_authorize_path %>
  <% else %>
    <%= link_to "Logout", destroy_user_session_path, method: 'delete' %>
  <% end %>
  <% if !current_user.nil? && (current_user.has_role? :admin) %>
    <%= link_to "Admin Page", admin_path %>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AptApp</title>
  <script src="//maps.google.com/maps/api/js?key=AIzaSyCioMZ6dc5oXrFK51xOhtG5DRJVxHZO-As"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <script src="//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" type="text/javascript"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p>
    <% if !current_user.nil? %>
      User: <%= current_user.email %>
      Roles:
      (<%= current_user.roles.pluck(:name).join(", ") %>)
    <% end %>
  </p>
  <p><%= notice %></p>
  <p><%= alert %></p>
<%= render '/layouts/header' %>
<%= yield %>

</body>
</html>